name: '602'
channels:
  - defaults
dependencies:
  - appnope=0.1.2=py39hecd8cb5_1001
  - argon2-cffi=20.1.0=py39h9ed2024_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=4.0.0=pyhd3eb1b0_0
  - ca-certificates=2021.10.26=hecd8cb5_2
  - certifi=2021.10.8=py39hecd8cb5_0
  - cffi=1.14.6=py39h2125817_0
  - debugpy=1.5.1=py39he9d5cce_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py39hecd8cb5_0
  - icu=58.2=h0a44026_3
  - importlib-metadata=4.8.2=py39hecd8cb5_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - ipykernel=6.4.1=py39hecd8cb5_1
  - ipython=7.29.0=py39h01d92e1_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.0=py39hecd8cb5_1
  - jinja2=3.0.2=pyhd3eb1b0_0
  - jpeg=9d=h9ed2024_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py39hecd8cb5_7
  - jupyter_client=7.0.6=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py39hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - markupsafe=2.0.1=py39h9ed2024_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h9ed2024_1000
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py39hecd8cb5_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=hca72f7f_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.6=py39hecd8cb5_0
  - openssl=1.1.1l=h9ed2024_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py39hecd8cb5_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.4=py39hecd8cb5_0
  - prometheus_client=0.12.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h23ab428_6
  - pyrsistent=0.18.0=py39hca72f7f_0
  - python=3.9.7=h88f2d9e_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyzmq=22.3.0=py39he9d5cce_2
  - qt=5.9.7=h468cd18_1
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - readline=8.1=h9ed2024_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py39hecd8cb5_0
  - sip=4.19.13=py39h23ab428_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hce871da_0
  - terminado=0.9.4=py39hecd8cb5_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h7bc2e8c_0
  - tornado=6.1=py39h9ed2024_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - tzdata=2021e=hda174b7_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39hecd8cb5_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - widgetsnbextension=3.5.1=py39hecd8cb5_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - astropy==4.3.1
    - charset-normalizer==2.0.7
    - colorama==0.4.4
    - configparser==5.1.0
    - crayons==0.4.0
    - cryptography==35.0.0
    - cycler==0.10.0
    - h11==0.12.0
    - idna==3.3
    - imageio==2.9.0
    - joblib==1.0.1
    - kiwisolver==1.3.2
    - matplotlib==3.4.3
    - mlxtend==0.19.0
    - networkx==2.6.3
    - numpy==1.21.2
    - opencv-python==4.5.3.56
    - outcome==1.1.0
    - pandas==1.3.3
    - patsy==0.5.2
    - pillow==8.3.2
    - pyerfa==2.0.0
    - pyopenssl==21.0.0
    - python-graphviz==0.19
    - pytz==2021.1
    - pywavelets==1.1.1
    - requests==2.26.0
    - scikit-image==0.18.3
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - seaborn==0.11.2
    - selenium==4.0.0
    - sniffio==1.2.0
    - sortedcontainers==2.4.0
    - statsmodels==0.13.1
    - threadpoolctl==2.2.0
    - tifffile==2021.10.12
    - trio==0.19.0
    - trio-websocket==0.9.2
    - urllib3==1.26.7
    - webdriver-manager==3.5.2
    - wsproto==1.0.0
prefix: /usr/local/Caskroom/miniconda/base/envs/602
